version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
  redis:
    #image: "redis:alpine"
    image: "redis"
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    #ports:
    #    - "6379:6379"